name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.2' # Define the elixir version [required]
        otp-version: '25.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install OS dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt install libfile-mimeinfo-perl shared-mime-info
    - name: Install Elixir dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Run dialyzer
      run: mix dialyzer
    - name: Run credo
      run: mix credo --strict
